#针对main.py、calibration.py等本地视频识别程序的配置文件

#本地调试配置
[debug]
#监测对象id
param_id = 10000   
#图像压缩率，值越高，质量越高，范围是1-95
quality = 20    
#是否需要生成被压缩的图片（方便远程调试）
need_compress = true
#是否只取1张照片
only_one_picture = true
rtsp_url1 = rtsp://admin:aSDFGH12@192.168.0.15:554/Streaming/Channels/101
rtsp_url2 = rtsp://admin:abcd1234@192.168.0.14:554/Streaming/Channels/101

#标定参数
[calibration]
#x方向上有多少个棋盘格
pattern_size_1 = 11
#y方向上有多少个棋盘格
pattern_size_2 = 8
#棋盘格实际尺寸(单位: mm)
actual_size = 22


#实际运行的主程序配置
[release]
#是否使用unet屋面板划分算法
use_unet = false
#是否保持第一张图片固定（即后续位移参照第一张图片来计算）
first_img = true
#硬盘录像机的rtsp url前缀，需要填写用户名，密码，ip，端口
rtsp_url_prefix = rtsp://admin:tncet702@192.168.0.10:554
#屋面板法向量 TODO，后续应该和监测对象绑定
normal_x = -0.05435280672552285
normal_y = -0.955125522876231
normal_z = -0.2911717842639709
#每次取视频流时，是否只取1张
use_one_picture = true
#训练模型的权重文件路径
weight_path = ./models/xxx