#位移识别程序运行时配置，可支持在不重启程序时，修改配置热生效，便于在每次计算的时候进行调整

#基本参数
[param]
#默认的位移最大值
max = 400
#是否只返回最大的值
only_max = true
#位移识别中ransac算法的阈值，单位pixel，减小这个阈值能够排除掉更多的异常点，但也有可能排除掉正常的点
ransac_reproj_threshold = 21
#是否显示位移值为0的点
show_zero_point = true
#允许前后两帧的两个点最大的水平xy方向距离
max_xy_distance = 15
#是否启用DBSCAN聚类算法，即同一区域中寻找最大
use_dbscan = false
#DBSCAN聚类算法中认为是一类的容忍值（单位mm）
dbscan_eps = 50


error_threshold = 1150
distance_threshold = 3.0

#颜色尺度
[color_scale]
#是否使用颜色尺度分级，如果使用的话，颜色就会随着位移值的增大，从绿色变为红色。如果不使用则每一个点采用随机颜色
use_color_scale = true
#下面的指标代表上限值  单位mm
#绿色 非常安全
green  = 5
#黄绿色 安全临界
yellowgreen = 10
#黄色 轻度危险
yellow = 20
#橙色 危险
orange = 30
#红色 重度危险 red 无上限值

#superpoint配置
[superpoint]
nms_dist = 4
conf_thresh = 0.008
#邻近距离的最大阙值，超过该阙值认为没匹配上
nn_thresh = 0.7    

